json.id @image.id
json.img_title @image.img_title
json.img_desc @image.img_desc
json.img_location @image.img_location
json.date_taken @image.date_taken
json.category @image.category
json.img_url @image.img.url
json.author_id @image.author_id
json.author_username @image.user.username
json.author_img @image.user.avatar.url
